;/*FB_PKG_DELIM*/

__d("FbShortsAggregationPageClickedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1435");b=d("FalcoLoggerInternal").create("fb_shorts_aggregation_page_clicked",a);e=b;g["default"]=e}),98);
__d("FbShortsInstagramDeeplinkFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1518");b=d("FalcoLoggerInternal").create("fb_shorts_instagram_deeplink",a);e=b;g["default"]=e}),98);
__d("FbShortsSaveReelFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2035");b=d("FalcoLoggerInternal").create("fb_shorts_save_reel",a);e=b;g["default"]=e}),98);
__d("FbShortsSeeLessFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1490");b=d("FalcoLoggerInternal").create("fb_shorts_see_less",a);e=b;g["default"]=e}),98);
__d("FbShortsUndoSeeLessFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1491");b=d("FalcoLoggerInternal").create("fb_shorts_undo_see_less",a);e=b;g["default"]=e}),98);
__d("FbShortsViewerOpenFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("936");b=d("FalcoLoggerInternal").create("fb_shorts_viewer_open",a);e=b;g["default"]=e}),98);
__d("SfvChainingNavigationExitFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("694");b=d("FalcoLoggerInternal").create("sfv_chaining_navigation_exit",a);e=b;g["default"]=e}),98);
__d("ShortsFollowFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1495");b=d("FalcoLoggerInternal").create("shorts_follow",a);e=b;g["default"]=e}),98);
__d("ShortsTapCreatorProfileFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1300");b=d("FalcoLoggerInternal").create("shorts_tap_creator_profile",a);e=b;g["default"]=e}),98);
__d("ShortsUnfollowFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1496");b=d("FalcoLoggerInternal").create("shorts_unfollow",a);e=b;g["default"]=e}),98);
__d("FanFundingStarsEventsTypedLoggerLite",["generateLiteTypedLogger"],(function(a,b,c,d,e,f){"use strict";e.exports=b("generateLiteTypedLogger")("logger:FanFundingStarsEventsLoggerConfig")}),null);